IT-1011
Sage-Bionetworks/admincentral-infra pull request #102
Opened 2020-12-03 01:04 UTC by xschildw

The two templates were run to setup the authorizer role and the VPN routes to the Synapse stacks account.
I created a new VPC for dev, 'config/prod/synapse-stack-vpn-routes.yaml' should setup the routes to get to it through VPN.
Note: the authorizer templates don't need to be re-run, the role is used by the Synapse VPC builder.

2020-12-03 20:23 UTC, zaro0508 requested changes

2020-12-03 20:23 UTC, zaro0508 commented on templates/synapse-stack-vpc-authorizer-role.yaml
> +Description: Create an authorizer role to authorize create/accept of a VPCPeering for a given AWS account
hmm, there's already a pattern and templates for peering.   we usually setup an authorization role in the spoke accounts (sandbox, scicomp, scipool,etc..)  not in the sophos hub (admincentral) account.   for example here a few peering templates in spokes:

* https://github.com/Sage-Bionetworks/sandbox-infra/blob/master/config/prod/peer-vpn-sandcastlevpc.yaml

* https://github.com/Sage-Bionetworks/scipool-infra/blob/develop/config/develop/peer-vpn-cesspoolvpc.yaml


To make a peering request from HUB to spoke VPCs you can just follow the pattern in config/prod/peering-*.yaml files, example:

* https://github.com/Sage-Bionetworks/admincentral-infra/blob/master/config/prod/peering-sandcastlevpc.yaml

* https://github.com/Sage-Bionetworks/admincentral-infra/blob/master/config/prod/peering-cesspoolvpc.yaml

2020-12-03 20:44 UTC, xschildw commented on templates/synapse-stack-vpc-authorizer-role.yaml
> +Description: Create an authorizer role to authorize create/accept of a VPCPeering for a given AWS account
I understand, but the way we did the peering for the Synapse stack VPCs is the opposite (the requestor is the spoke and the acceptor is the hub). The roles already exists to cover the Synapse Prod and Dev accounts, I'm just capturing the template because I did not find it in the source. 
Likewise for adding the routes from VPN to Synapse stack VPCs, I think this is part of VPCPeer.yaml in the IT pattern but since we did not use that there was a separate template that only added the routes. In this case, I'm actually adding a config since I need to add routes to a new Synapse stack Dev VPC I have created. Will need to add another config for Prod later.

2020-12-04 16:37 UTC, zaro0508 requested changes

2020-12-04 16:37 UTC, zaro0508 commented on templates/synapse-stack-vpc-authorizer-role.yaml
> +Description: Create an authorizer role to authorize create/accept of a VPCPeering for a given AWS account
ok.  so is there a template on the spoke side that's makes the peering request?  Also I don't see how this role is used on the hub side.  Is there a current or soon to be template  that applies this role to something?

2020-12-04 16:37 UTC, zaro0508 commented on config/prod/synapse-stack-dev-vpn-routes.yaml
> +  VPCPeeringConnectionId: pcx-08e34f0e8c7e984b8
how does this peering request get made?

2020-12-04 16:37 UTC, zaro0508 commented on templates/synapse-stack-vpn-routes.yaml
> +# Template source https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/solutions/VPCPeering/VPCPeer.json
this comment doesn't make sense.

2020-12-04 16:37 UTC, zaro0508 commented on templates/synapse-stack-vpn-routes.yaml
> +  This template create a lambda function and use it to accept a cross account
no lambda function in here.

2020-12-04 16:37 UTC, zaro0508 commented on templates/synapse-stack-vpn-routes.yaml
> +Metadata: {}
this is not needed.

2020-12-04 17:46 UTC, xschildw commented on templates/synapse-stack-vpc-authorizer-role.yaml
> +Description: Create an authorizer role to authorize create/accept of a VPCPeering for a given AWS account
Correct, the spoke VPC is setup by a Java app that generates and applies a template (one of the apps in https://github.com/Sage-Bionetworks/Synapse-Stack-Builder).
The ARN of the role is specified when we create the peering connection (from the spoke), see https://github.com/Sage-Bionetworks/Synapse-Stack-Builder/blob/develop/src/main/resources/templates/vpc/main-vpc.json.vtp#L30-L52 .

2020-12-04 17:49 UTC, xschildw commented on config/prod/synapse-stack-dev-vpn-routes.yaml
> +  VPCPeeringConnectionId: pcx-08e34f0e8c7e984b8
Request made from cloudformation stack run by app (Stack-Builder ref in previous comment)

2020-12-04 17:50 UTC, xschildw commented on templates/synapse-stack-vpn-routes.yaml
> +# Template source https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/solutions/VPCPeering/VPCPeer.json
Deleting.

2020-12-04 17:51 UTC, xschildw commented on templates/synapse-stack-vpn-routes.yaml
> +  This template create a lambda function and use it to accept a cross account
Changed, must have lifted the code from your version (VPCPeer.yaml)

2020-12-04 17:51 UTC, xschildw commented on templates/synapse-stack-vpn-routes.yaml
> +Metadata: {}
Same.

2020-12-04 18:34 UTC, zaro0508 requested changes
hmm, so spoke makes the peering request but from looking at these templates it's still not clear to me how the HUB accepts the peering request.  do you know?

2020-12-04 18:34 UTC, zaro0508 commented on config/prod/synapse-stack-dev-vpn-routes.yaml
> +  VPCPeeringConnectionId: pcx-08e34f0e8c7e984b8
could we add a comment about this?

2021-01-07 20:15 UTC, zaro0508 approved these changes

2021-01-07 21:22 UTC, merged